name: 'NeuroStreak_0.0.1'

head:
  spectral_dim: 64
  wavelet_dim: 32
  embedding_dim: 128

backbone:
  hidden_dim: 32
  num_heads: 8
  depth: 8


embedding:
  max_amp: 50
  step: 0.5
  wavelet: 'gaus2'
