name: 'NeuroStreak_0.0.1'

head:
  spectral_dim: 64
  wavelet_dim: 32
  embedding_dim: 128

backbone:
  hidden_dim: 32
  num_heads: 8
  depth: 8


#embedding:
#  wavelet: 'morlet'
#  mu: 0.5
#  fs: 102e9
#  nv: 128


embedding:
  wavelet: 'gaus1'
  max_amp: 101
  step: 1